# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cube.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "cube.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ncube.proto\x12\x07service"\x1d\n\x0b\x43ubeRequest\x12\x0e\n\x06number\x18\x01 \x01(\x01"\x1b\n\tCubeReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\x44\n\x0b\x43ubeService\x12\x35\n\x07GetCube\x12\x14.service.CubeRequest\x1a\x12.service.CubeReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "cube_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CUBEREQUEST"]._serialized_start = 23
    _globals["_CUBEREQUEST"]._serialized_end = 52
    _globals["_CUBEREPLY"]._serialized_start = 54
    _globals["_CUBEREPLY"]._serialized_end = 81
    _globals["_CUBESERVICE"]._serialized_start = 83
    _globals["_CUBESERVICE"]._serialized_end = 151
# @@protoc_insertion_point(module_scope)
