version: "3.9"

services:
  django:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./django_project:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - database

  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./fastapi_app:/workspace
    ports:
      - "8001:8001"

  database:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
